name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test code base
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.17.x'
    - run: npm install
    - run: npm start